---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: ClusterAddon
metadata:
  name: portworx
  labels:
    kubeaddons.mesosphere.io/name: portworx
    kubeaddons.mesosphere.io/provides: portworx
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "1.0.0-3"
    appversion.kubeaddons.mesosphere.io/portworx: "2.5.1"
    values.chart.helm.kubeaddons.mesosphere.io/portworx: "https://raw.githubusercontent.com/portworx/helm/master/charts/portworx/values.yaml"
spec:
  namespace: kube-system
  requires:
    - matchLabels:
        kubeaddons.mesosphere.io/name: defaultstorageclass-protection
  kubernetes:
    minSupportedVersion: v1.15.6
  cloudProvider:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: gcp
      enabled: true
    - name: docker
      enabled: false
    - name: none
      enabled: true
  chartReference:
    chart: portworx
    repo: https://github.com/portworx/helm/charts
    version: 1.0.0
    values: |
      ---
      deploymentType: oci                     # accepts "oci" or "docker"
      imageType: none                         #
      imageVersion: 2.5.1                     # Version of the PX Image.

      openshiftInstall: false                 # Defaults to false for installing Portworx on Openshift .
      isTargetOSCoreOS: false                 # Is your target OS CoreOS? Defaults to false.
      pksInstall: false                       # installation on PKS (Pivotal Container Service)
      EKSInstall: false                     # installation on EKS.
      AKSInstall: false                      # installation on AKS
      etcdEndPoint:                         # The ETCD endpoint. Should be in the format etcd:http://<your-etcd-endpoint>:2379. If there are multiple etcd endpoints they need to be ";" seperated.
                                            # the default value is empty since it requires to be explicity set using either the --set option of -f values.yaml.
      clusterName: mycluster                # This is the default. please change it to your cluster name.
      usefileSystemDrive: false             # true/false Instructs PX to use an unmounted Drive even if it has a filesystem.
      usedrivesAndPartitions: false         # Defaults to false. Change to true and PX will use unmounted drives and partitions.
      secretType: k8s                       # Defaults to k8s, but can be kvdb/k8s/aws-kms/vault/ibm-kp. It is autopopulated to ibm-kp if the environment is IKS.
      drives: none                          # NOTE: This is a ";" seperated list of drives. For eg: "/dev/sda;/dev/sdb;/dev/sdc" Defaults to use -A switch.
      dataInterface: none                   # Name of the interface <ethX>
      managementInterface: none             # Name of the interface <ethX>
      envVars: none                         # NOTE: This is a ";" seperated list of environment variables. For eg: MYENV1=myvalue1;MYENV2=myvalue2

      stork: true                           # Use Stork https://docs.portworx.com/scheduler/kubernetes/stork.html for hyperconvergence.
      storkVersion: 2.4.0

      customRegistryURL:
      registrySecret:

      lighthouse: true
      lighthouseVersion: 2.0.7
      lighthouseSyncVersion: 2.0.7
      lighthouseStorkConnectorVersion: 2.0.7
      monitoring: false

      journalDevice:

      deployOnMaster:  false                # For POC only
      csi: true                             # Enable CSI

      internalKVDB: false                   # internal KVDB

      etcd:
        credentials: none                   # Username and password for ETCD authentication in the form user:password
        certPath: none                      # Base path where the certificates are placed. (example: if the certificates ca,crt and the key are in /etc/pwx/etcdcerts the value should be provided as /etc/pwx/etcdcerts)
        ca: none                            # Location of CA file for ETCD authentication. Should be /path/to/server.ca
        cert: none                          # Location of certificate for ETCD authentication. Should be /path/to/server.crt
        key: none                           # Location of certificate key for ETCD authentication Should be /path/to/servery.key
      consul:
        token: none                         # ACL token value used for Consul authentication. (example: 398073a8-5091-4d9c-871a-bbbeb030d1f6)

      tolerations:                          # Add tolerations
        - operator: Exists
          effect: NoSchedule
        - operator: Exists
          effect: NoExecute
        - operator: Exists
          key: CriticalAddonsOnly

      serviceAccount:
        hook:
          create: true
          name:

      clusterToken:
        create: false                    # Create cluster token
        secretName: px-vol-encryption    # Name of kubernetes secret to be created. Requires clusterToken.create to be true.
        serviceAccountName: px-create-cluster-token # Service account name to use for post-install hook to create cluster token

      replicas: 3                         # Replica count for pvc-controller, stork, stork-scheduler.