---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: ClusterAddon
metadata:
  name: efs-csi-driver
  labels:
    kubeaddons.mesosphere.io/name: efs-csi-driver
    kubeaddons.mesosphere.io/provides: efs-csi-driver
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "1.0.0-1"
    appversion.kubeaddons.mesosphere.io/efs-csi-driver: "1.0.0"
    values.chart.helm.kubeaddons.mesosphere.io/efs-csi-driver: "https://raw.githubusercontent.com/kubernetes-sigs/aws-efs-csi-driver/f2fc7cee45cf87ad8bd73ccc3280b99e1b75dc8b/helm/values.yaml"
spec:
  namespace: kube-system
  kubernetes:
    minSupportedVersion: v1.15.6
  cloudProvider:
    - name: aws
      enabled: true
  chartReference:
    chart: aws-efs-csi-driver
    repo: https://kubernetes-sigs.github.io
    version: 0.3.0
    values: |
      ---
      replicaCount: 2
      image:
        repository: amazon/aws-efs-csi-driver
        tag: "v1.0.0"
        pullPolicy: IfNotPresent
      sidecars:
        livenessProbeImage:
          repository: quay.io/k8scsi/livenessprobe
          tag: "v2.0.0"
        nodeDriverRegistrarImage:
          repository: quay.io/k8scsi/csi-node-driver-registrar
          tag: "v1.3.0"
        csiProvisionerImage:
          repository: k8s.gcr.io/sig-storage/csi-provisioner
          tag: "v2.0.2"
      podAnnotations: {}
        # iam.amazonaws.com/role: efs-csi-driver-role
      resources: {}
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
      affinity: {}
      node:
        podAnnotations: {}
        tolerations: []
      logLevel: 5
      hostAliases: {}
        # for cross VPC EFS, you need to poison or overwrite the DNS for the efs volume as per
        # https://docs.aws.amazon.com/efs/latest/ug/efs-different-vpc.html#wt6-efs-utils-step3
        # implementing the suggested solution found here:
        # https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/240#issuecomment-676849346
        # EFS Vol ID, IP, Region
        # "fs-01234567":
        #   ip: 10.10.2.2
        #   region: us-east-2
      dnsPolicy: ""
      dnsConfig: {}
      serviceAccount:
        # Specifies whether a service account should be created
        create: true
        annotations: {}
        ## Enable if EKS IAM for SA is used
        #  eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/efs-csi-role
        name: efs-csi-controller-sa
